// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BioPatML-FSharp")>]
[<assembly: AssemblyProductAttribute("BioPatML-FSharp")>]
[<assembly: AssemblyDescriptionAttribute("An implementation of BioPatML in FSharp")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BioPatML-FSharp"
    let [<Literal>] AssemblyProduct = "BioPatML-FSharp"
    let [<Literal>] AssemblyDescription = "An implementation of BioPatML in FSharp"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
